# .streamlit/config.toml

[theme]
# Primary accent color for interactive elements.
primaryColor="#4A90E2"  # A calm, modern blue

# Background color for the main content area.
backgroundColor="#F0F2F6" # Light grey, common in modern UIs

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor="#FFFFFF" # White for cards, expanders, sidebar

# Text color for the main content area.
textColor="#262730" # Dark grey for readability

# Font family for all text in the app.
# Options: "sans serif", "serif", or "monospace"
# For custom fonts, you'll need to load them via CSS.
font="sans serif"

[server]
# Allows your app to be embedded in iframes (optional, but good for sharing)
enableCORS = true
enableXsrfProtection = true

[logger]
# Sets the logging level (useful for debugging)
level = "info" # Options: "error", "warning", "info", "debug"

[client]
# Show a warning if the app is busy
showWarningOnDirectExecution = false
